### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by pkphilip** [OUISRC/Rust-webapp-starter#5]
I am getting this error when I run "cargo run".  I am using Rust 1.26.0-nightly (e5277c145 2018-03-28)

Pasting an excerpt below:

>    Compiling tokio-io v0.1.6
>    Compiling http v0.1.5
>    Compiling mio-uds v0.6.4
>    Compiling generic-array v0.9.0
>    Compiling parking_lot v0.4.8
>    Compiling phf_shared v0.7.21
>    Compiling mime v0.3.5
> error[E0034]: multiple applicable items in scope
>    --> /home/prem/.cargo/registry/src/github.com-1ecc6299db9ec823/http-0.1.5/src/method.rs:325:9
>     |
> 325 |         Method::try_from(t.as_bytes())
>     |         ^^^^^^^^^^^^^^^^ multiple `try_from` found
>     |
>     = note: candidate #1 is defined in an impl of the trait `std::convert::TryFrom` for the type `_`
> note: candidate #2 is defined in the trait `convert::HttpTryFrom`
>    --> /home/prem/.cargo/registry/src/github.com-1ecc6299db9ec823/http-0.1.5/src/convert.rs:22:5
>     |
> 22  |     fn try_from(t: T) -> Result<Self, Self::Error>;
>     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     = help: to disambiguate the method call, write `convert::HttpTryFrom::try_from(...)` instead
> 
> error[E0034]: multiple applicable items in scope
>    --> /home/prem/.cargo/registry/src/github.com-1ecc6299db9ec823/http-0.1.5/src/method.rs:334:9
>     |
> 334 |         Method::try_from(t)
>     |         ^^^^^^^^^^^^^^^^ multiple `try_from` found
>     |
>     = note: candidate #1 is defined in an impl of the trait `std::convert::TryFrom` for the type `_`
> note: candidate #2 is defined in the trait `convert::HttpTryFrom`
>    --> /home/prem/.cargo/registry/src/github.com-1ecc6299db9ec823/http-0.1.5/src/convert.rs:22:5
>     |
> 22  |     fn try_from(t: T) -> Result<Self, Self::Error>;
>     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     = help: to disambiguate the method call, write `convert::HttpTryFrom::try_from(...)` instead
> 
> error[E0034]: multiple applicable items in scope
>    --> /home/prem/.cargo/registry/src/github.com-1ecc6299db9ec823/http-0.1.5/src/request.rs:767:19
>     |
> 767 |             match Method::try_from(method) {
>     |                   ^^^^^^^^^^^^^^^^ multiple `try_from` found
>     |
>     = note: candidate #1 is defined in an impl of the trait `std::convert::TryFrom` for the type `_`
> note: candidate #2 is defined in the trait `convert::HttpTryFrom`
>    --> /home/prem/.cargo/registry/src/github.com-1ecc6299db9ec823/http-0.1.5/src/convert.rs:22:5
>     |
> 22  |     fn try_from(t: T) -> Result<Self, Self::Error>;
>     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     = help: to disambiguate the method call, write `convert::HttpTryFrom::try_from(...)` instead
> 
> error[E0034]: multiple applicable items in scope
>    --> /home/prem/.cargo/registry/src/github.com-1ecc6299db9ec823/http-0.1.5/src/request.rs:796:19
>     |
> 796 |             match Uri::try_from(uri) {
>     |                   ^^^^^^^^^^^^^ multiple `try_from` found
>     |
>     = note: candidate #1 is defined in an impl of the trait `std::convert::TryFrom` for the type `_`
> note: candidate #2 is defined in the trait `convert::HttpTryFrom`
>    --> /home/prem/.cargo/registry/src/github.com-1ecc6299db9ec823/http-0.1.5/src/convert.rs:22:5
>     |
> 22  |     fn try_from(t: T) -> Result<Self, Self::Error>;
>     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     = help: to disambiguate the method call, write `convert::HttpTryFrom::try_from(...)` instead
> 
> error[E0034]: multiple applicable items in scope
>    --> /home/prem/.cargo/registry/src/github.com-1ecc6299db9ec823/http-0.1.5/src/request.rs:851:19
>     |
> 851 |             match HeaderName::try_from(key) {
>     |                   ^^^^^^^^^^^^^^^^^^^^ multiple `try_from` found
>     |
>     = note: candidate #1 is defined in an impl of the trait `std::convert::TryFrom` for the type `_`
> note: candidate #2 is defined in the trait `convert::HttpTryFrom`
>    --> /home/prem/.cargo/registry/src/github.com-1ecc6299db9ec823/http-0.1.5/src/convert.rs:22:5
>     |
> 22  |     fn try_from(t: T) -> Result<Self, Self::Error>;
>     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     = help: to disambiguate the method call, write `convert::HttpTryFrom::try_from(...)` instead
> 
> error[E0034]: multiple applicable items in scope
>    --> /home/prem/.cargo/registry/src/github.com-1ecc6299db9ec823/http-0.1.5/src/request.rs:853:27
>     |
> 853 |                     match HeaderValue::try_from(value) {
>     |                           ^^^^^^^^^^^^^^^^^^^^^ multiple `try_from` found
>     |
>     = note: candidate #1 is defined in an impl of the trait `std::convert::TryFrom` for the type `_`
> note: candidate #2 is defined in the trait `convert::HttpTryFrom`
>    --> /home/prem/.cargo/registry/src/github.com-1ecc6299db9ec823/http-0.1.5/src/convert.rs:22:5
>     |
> 22  |     fn try_from(t: T) -> Result<Self, Self::Error>;
>     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     = help: to disambiguate the method call, write `convert::HttpTryFrom::try_from(...)` instead
> 
> error[E0034]: multiple applicable items in scope
>    --> /home/prem/.cargo/registry/src/github.com-1ecc6299db9ec823/http-0.1.5/src/response.rs:564:19
>     |
> 564 |             match StatusCode::try_from(status) {
>     |                   ^^^^^^^^^^^^^^^^^^^^ multiple `try_from` found
>     |
>     = note: candidate #1 is defined in an impl of the trait `std::convert::TryFrom` for the type `_`
> note: candidate #2 is defined in the trait `convert::HttpTryFrom`
>    --> /home/prem/.cargo/registry/src/github.com-1ecc6299db9ec823/http-0.1.5/src/convert.rs:22:5
>     |
> 22  |     fn try_from(t: T) -> Result<Self, Self::Error>;
>     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     = help: to disambiguate the method call, write `convert::HttpTryFrom::try_from(...)` instead
> 
> error[E0034]: multiple applicable items in scope
>    --> /home/prem/.cargo/registry/src/github.com-1ecc6299db9ec823/http-0.1.5/src/response.rs:619:19
>     |
> 619 |             match HeaderName::try_from(key) {
>     |                   ^^^^^^^^^^^^^^^^^^^^ multiple `try_from` found
>     |
>     = note: candidate #1 is defined in an impl of the trait `std::convert::TryFrom` for the type `_`
> note: candidate #2 is defined in the trait `convert::HttpTryFrom`
>    --> /home/prem/.cargo/registry/src/github.com-1ecc6299db9ec823/http-0.1.5/src/convert.rs:22:5
>     |
> 22  |     fn try_from(t: T) -> Result<Self, Self::Error>;
>     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     = help: to disambiguate the method call, write `convert::HttpTryFrom::try_from(...)` instead
> 
> error[E0034]: multiple applicable items in scope
>    --> /home/prem/.cargo/registry/src/github.com-1ecc6299db9ec823/http-0.1.5/src/response.rs:621:27
>     |
> 621 |                     match HeaderValue::try_from(value) {
>     |                           ^^^^^^^^^^^^^^^^^^^^^ multiple `try_from` found
>     |
>     = note: candidate #1 is defined in an impl of the trait `std::convert::TryFrom` for the type `_`
> note: candidate #2 is defined in the trait `convert::HttpTryFrom`
>    --> /home/prem/.cargo/registry/src/github.com-1ecc6299db9ec823/http-0.1.5/src/convert.rs:22:5
>     |
> 22  |     fn try_from(t: T) -> Result<Self, Self::Error>;
>     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     = help: to disambiguate the method call, write `convert::HttpTryFrom::try_from(...)` instead
> 
> error: aborting due to 9 previous errors
> 
> For more information about this error, try `rustc --explain E0034`.
> error: Could not compile `http`.
> warning: build failed, waiting for other jobs to finish...
> error: build failed
>

**Comment by krircc** [comment]
@pkphilip it doesn't need nightly rust. it's ok on my machine :
nightly rustc 1.27.0-nightly (056f589fb 2018-04-07)
stable rustc 1.25.0 (84203cac6 2018-03-25)

**Comment by pkphilip** [comment]
Can confirm that the build does complete successfully with rust stable 1.25 .0 while it fails with rust nightly.

**Comment by pkphilip** [comment]
Thank you. Yes, the build is succeeding with 1.27.0-nightly (056f589fb 2018-04-07).

I appreciate your work.
